# Generated by Django 6.0.3 on 2026-05-06 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalloan',
            name='loan_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_id',
            field=models.TextField(),
        ),
    ]
