# Generated by Django 6.0.3 on 2026-05-06 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_alter_historicalloan_loan_id_alter_loan_loan_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalloan',
            old_name='commnent',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='commnent',
            new_name='comment',
        ),
        migrations.AlterField(
            model_name='historicalloan',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
