# Generated by Django 6.0.3 on 2026-05-07 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_rename_commnent_historicalloan_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalloan',
            old_name='loan_id',
            new_name='loan',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='loan_id',
            new_name='loan',
        ),
    ]
