# Generated by Django 6.0.3 on 2026-05-17 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_rename_loan_id_historicalloan_loan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commercial_loan',
            fields=[
                ('loan_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='loan.loan')),
            ],
            options={
                'verbose_name': 'Commercial Loan',
                'verbose_name_plural': 'Commercial Loans',
            },
            bases=('loan.loan',),
        ),
        migrations.CreateModel(
            name='Residential_loan',
            fields=[
                ('loan_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='loan.loan')),
            ],
            options={
                'verbose_name': 'Residential Loan',
                'verbose_name_plural': 'Residential Loans',
            },
            bases=('loan.loan',),
        ),
    ]
