# Generated by Django 6.0.3 on 2026-05-26 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0006_historicalcommercial_loan_historicalresidential_loan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commercial_loan',
            options={'ordering': ['-created_at'], 'verbose_name': 'Commercial Loan', 'verbose_name_plural': 'Commercial Loans'},
        ),
        migrations.AlterModelOptions(
            name='residential_loan',
            options={'ordering': ['-created_at'], 'verbose_name': 'Residential Loan', 'verbose_name_plural': 'Residential Loans'},
        ),
        migrations.AddField(
            model_name='historicalcommercial_loan',
            name='is_active',
            field=models.BooleanField(default=True, help_text='default True, set to False when loan is closed'),
        ),
        migrations.AddField(
            model_name='historicalloan',
            name='is_active',
            field=models.BooleanField(default=True, help_text='default True, set to False when loan is closed'),
        ),
        migrations.AddField(
            model_name='historicalresidential_loan',
            name='is_active',
            field=models.BooleanField(default=True, help_text='default True, set to False when loan is closed'),
        ),
        migrations.AddField(
            model_name='loan',
            name='is_active',
            field=models.BooleanField(default=True, help_text='default True, set to False when loan is closed'),
        ),
        migrations.AlterField(
            model_name='historicalcommercial_loan',
            name='location',
            field=models.TextField(blank=True, help_text='Used for sharding, auto-calculated it is not provided', null=True),
        ),
        migrations.AlterField(
            model_name='historicalloan',
            name='location',
            field=models.TextField(blank=True, help_text='Used for sharding, auto-calculated it is not provided', null=True),
        ),
        migrations.AlterField(
            model_name='historicalresidential_loan',
            name='location',
            field=models.TextField(blank=True, help_text='Used for sharding, auto-calculated it is not provided', null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='location',
            field=models.TextField(blank=True, help_text='Used for sharding, auto-calculated it is not provided', null=True),
        ),
    ]
