# Generated by Django 6.0.3 on 2026-05-26 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0007_alter_commercial_loan_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalcommercial_loan',
            name='location',
            field=models.TextField(help_text='Auto-calculated if wherabout is not provided', null=True),
        ),
        migrations.AlterField(
            model_name='historicalloan',
            name='location',
            field=models.TextField(help_text='Auto-calculated if wherabout is not provided', null=True),
        ),
        migrations.AlterField(
            model_name='historicalresidential_loan',
            name='location',
            field=models.TextField(help_text='Auto-calculated if wherabout is not provided', null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='location',
            field=models.TextField(help_text='Auto-calculated if wherabout is not provided', null=True),
        ),
    ]
