# Generated by Django 6.0.3 on 2026-05-26 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0008_alter_historicalcommercial_loan_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalcommercial_loan',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalloan',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalresidential_loan',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
