# Generated by Django 6.0.3 on 2026-05-26 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0009_historicalcommercial_loan_closed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalcommercial_loan',
            name='closed_at',
            field=models.DateField(blank=True, help_text='Date when loan was closed. Set when is_active is set to False.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalloan',
            name='closed_at',
            field=models.DateField(blank=True, help_text='Date when loan was closed. Set when is_active is set to False.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalresidential_loan',
            name='closed_at',
            field=models.DateField(blank=True, help_text='Date when loan was closed. Set when is_active is set to False.', null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='closed_at',
            field=models.DateField(blank=True, help_text='Date when loan was closed. Set when is_active is set to False.', null=True),
        ),
    ]
