# Generated by Django 6.0.3 on 2026-05-26 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0010_alter_historicalcommercial_loan_closed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercial_loan',
            name='has_Assignment_of_Rents',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commercial_loan',
            name='has_UCC1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcommercial_loan',
            name='has_Assignment_of_Rents',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcommercial_loan',
            name='has_UCC1',
            field=models.BooleanField(default=False),
        ),
    ]
