# Generated by Django 6.0.3 on 2026-05-27 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0011_commercial_loan_has_assignment_of_rents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalcommercial_loan',
            name='location',
            field=models.TextField(blank=True, help_text='Auto-calculated if wherabout is not provided', null=True),
        ),
        migrations.AlterField(
            model_name='historicalloan',
            name='location',
            field=models.TextField(blank=True, help_text='Auto-calculated if wherabout is not provided', null=True),
        ),
        migrations.AlterField(
            model_name='historicalresidential_loan',
            name='location',
            field=models.TextField(blank=True, help_text='Auto-calculated if wherabout is not provided', null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='location',
            field=models.TextField(blank=True, help_text='Auto-calculated if wherabout is not provided', null=True),
        ),
    ]
