# Generated by Django 6.0.3 on 2026-08-18 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0013_alter_historicalcommercial_loan_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalcommercial_loan',
            name='id',
            field=models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicalloan',
            name='id',
            field=models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicalresidential_loan',
            name='id',
            field=models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
