# Generated by Codex on 2026-08-31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0014_alter_historicalcommercial_loan_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
