"""
Django settings for Loantracker project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(dotenv_path=BASE_DIR / '.env')

DB_HOST = os.getenv('DB_HOST') or os.getenv('BACKEND')
DB_NAME = os.getenv('DB_NAME') or os.getenv('DB')
DB_USER = os.getenv('DB_USER') or os.getenv('user')
DB_PASSWORD = os.getenv('DB_PASSWORD') or os.getenv('password', '')
DB_PORT = int(os.getenv('DB_PORT', '5432'))
DB_USE_IAM = os.getenv('DB_USE_IAM', 'false').lower() in ('1', 'true', 'yes')
AWS_REGION = os.getenv('AWS_REGION', 'us-east-2')
SECRET = os.getenv('SECRET')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = SECRET

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'simple_history',
    'import_export',
    'api',
    'api.loan',
    'api.insurance',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://192.168.1.164:5173", 
]
ROOT_URLCONF = 'Loantracker.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Loantracker.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

import boto3
import psycopg2

def _rds_iam_token():
    client = boto3.client('rds', region_name='us-east-2')
    return client.generate_db_auth_token(
        DBHostname='database-1.cluster-cnkam8yss8hx.us-east-2.rds.amazonaws.com',
        Port=5432,
        DBUsername='postgres',
        Region='us-east-2',
    )

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.postgresql",
#         "HOST": DB_HOST or 'database-1.cluster-cnkam8yss8hx.us-east-2.rds.amazonaws.com',
#         "PORT": DB_PORT,
#         "NAME": DB_NAME or 'postgres',
#         "USER": DB_USER or 'postgres',
#         "PASSWORD": DB_PASSWORD or (_rds_iam_token() if DB_USE_IAM else ''),
#         "OPTIONS": {
#             "sslmode": "require",
#         },
#     }
# }

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": "mydatabase",
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


# FOR IMPORT EXPORT
LOGGING = {
    "version": 1,
    "handlers": {
        "console": {"level": "DEBUG", "class": "logging.StreamHandler"},
    },
    "loggers": {
        "django.db.backends": {"level": "INFO", "handlers": ["console"]},
        "import_export": {
            "handlers": ["console"],
            "level": "INFO",
        },
    },
}


