# Generated by Django 6.0.3 on 2026-05-07 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinsurance',
            name='loan_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='loan_id',
            field=models.TextField(),
        ),
    ]
