# Generated by Django 6.0.3 on 2026-05-07 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_alter_historicalinsurance_loan_id_and_more'),
        ('loan', '0003_rename_commnent_historicalloan_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinsurance',
            name='loan_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='loan.loan'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='loan_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to='loan.loan'),
        ),
    ]
