# Generated by Django 6.0.3 on 2026-05-07 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_alter_historicalinsurance_loan_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalinsurance',
            old_name='loan_id',
            new_name='loan',
        ),
        migrations.RenameField(
            model_name='insurance',
            old_name='loan_id',
            new_name='loan',
        ),
    ]
