# Generated by Django 6.0.3 on 2026-05-10 05:05

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0004_rename_loan_id_historicalinsurance_loan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('contact_info', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('emails', models.JSONField(blank=True, help_text="List of email addresses, e.g., ['primary@email.com', 'secondary@email.com']", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='historicalinsurance',
            name='insurance_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='insurance_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalinsurance',
            name='insurance_provider',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='historicalinsurance',
            name='insurance_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalinsurance',
            name='insurance_type',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='insurance_provider',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='insurance_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='insurance_type',
            field=models.CharField(max_length=128),
        ),
        migrations.CreateModel(
            name='HistoricalInsuranceAgency',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('contact_info', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('emails', models.JSONField(blank=True, help_text="List of email addresses, e.g., ['primary@email.com', 'secondary@email.com']", null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical insurance agency',
                'verbose_name_plural': 'historical insurance agencys',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='historicalinsurance',
            name='insurance_agent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='insurance.insuranceagency'),
        ),
        migrations.AddField(
            model_name='insurance',
            name='insurance_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='insurance.insuranceagency'),
        ),
    ]
