# Generated by Django 6.0.3 on 2026-05-10 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0005_insuranceagency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalinsuranceagency',
            name='address',
        ),
        migrations.RemoveField(
            model_name='historicalinsuranceagency',
            name='emails',
        ),
        migrations.RemoveField(
            model_name='historicalinsuranceagency',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='insuranceagency',
            name='address',
        ),
        migrations.RemoveField(
            model_name='insuranceagency',
            name='emails',
        ),
        migrations.RemoveField(
            model_name='insuranceagency',
            name='phone',
        ),
    ]
