# Generated by Django 6.0.3 on 2026-05-21 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0007_alter_historicalinsurance_insurance_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinsurance',
            name='insurance_type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='insurance_type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
