# Generated by Django 6.0.3 on 2026-08-18 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0009_alter_historicalinsurance_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalinsurance',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Insurance', 'verbose_name_plural': 'historical Insurances'},
        ),
        migrations.AlterModelOptions(
            name='historicalinsuranceagency',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Insurance Agency', 'verbose_name_plural': 'historical Insurance Agencies'},
        ),
        migrations.AlterModelOptions(
            name='insurance',
            options={'verbose_name': 'Insurance', 'verbose_name_plural': 'Insurances'},
        ),
        migrations.AlterModelOptions(
            name='insuranceagency',
            options={'verbose_name': 'Insurance Agency', 'verbose_name_plural': 'Insurance Agencies'},
        ),
        migrations.AlterField(
            model_name='historicalinsurance',
            name='id',
            field=models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicalinsuranceagency',
            name='id',
            field=models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='insuranceagency',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
